# Generated by Django 3.1.6 on 2021-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20210314_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True),
        ),
    ]
