# Generated by Django 3.1.6 on 2021-03-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uterType',
            field=models.CharField(choices=[('Adviser', '상담사'), ('Normal', '일반')], max_length=7, null=True),
        ),
    ]
