# Generated by Django 3.1.6 on 2021-03-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_customuser_utertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uterType',
            new_name='userType',
        ),
    ]
