# Generated by Django 3.1.6 on 2021-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_auto_20210323_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthDate',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
    ]
