# Generated by Django 3.1.6 on 2021-05-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0014_auto_20210503_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
    ]
