# Generated by Django 3.1.6 on 2021-05-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_auto_20210503_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/default.jpg', null=True, upload_to=''),
        ),
    ]
