# Generated by Django 3.1.6 on 2021-03-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tendancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='아카이빙 날짜/시각')),
                ('answer', models.CharField(max_length=100, null=True, verbose_name='정답 리스트')),
            ],
        ),
    ]
