# Generated by Django 3.1.6 on 2021-05-12 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tendancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='아카이빙 날짜/시각')),
                ('answer', models.CharField(max_length=100, null=True, verbose_name='정답 리스트')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateField(auto_now_add=True, verbose_name='아카이빙 날짜/시각')),
                ('emotions', models.CharField(max_length=100, null=True, verbose_name='감정 리스트')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('weather', models.CharField(choices=[('clear sky', '맑음'), ('few clouds', '흐림'), ('scattered clouds', '흐림'), ('broken clouds', '흐림'), ('shower rain', '비'), ('rain', '비'), ('thunderstorm', '번개'), ('snow', '눈'), ('mist', '안개')], max_length=20, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
