# Generated by Django 3.1.6 on 2021-05-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='weather',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
