# Generated by Django 3.1.6 on 2021-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210512_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='pubdate',
            field=models.DateField(verbose_name='아카이빙 날짜/시각'),
        ),
    ]
