# Generated by Django 3.1.6 on 2021-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210513_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='weather',
            field=models.IntegerField(null=True),
        ),
    ]
