# Generated by Django 3.1.6 on 2021-05-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
