# Generated by Django 3.1.6 on 2021-05-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_emotion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
