# Generated by Django 3.1.6 on 2021-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20210513_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='제목')),
                ('emotion', models.IntegerField(null=True)),
                ('iframe_url', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emotion',
            name='pubdate',
            field=models.DateField(auto_now_add=True, verbose_name='아카이빙 날짜/시각'),
        ),
    ]
