# Generated by Django 3.1.6 on 2021-05-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20210502_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
