# Generated by Django 3.1.6 on 2021-05-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20210513_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='music_emotion', to='analysis.Emotion'),
        ),
    ]
