# Generated by Django 3.1.6 on 2021-05-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_music_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='connection',
        ),
        migrations.AddField(
            model_name='emotion',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='music_emotion', to='analysis.Music'),
        ),
    ]
