# Generated by Django 3.1.6 on 2021-05-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='creator',
            new_name='creater',
        ),
    ]
