# Generated by Django 3.1.6 on 2021-05-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210517_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='state',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
