# Generated by Django 3.1.6 on 2021-05-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='numbers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
