# Generated by Django 3.1.6 on 2021-05-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='state',
        ),
    ]
