# Generated by Django 3.1.6 on 2021-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210517_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='방 이름')),
                ('numbers', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
