# Generated by Django 3.1.6 on 2021-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='pubdate',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='날짜'),
        ),
    ]
