# Generated by Django 3.1.6 on 2021-05-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
